name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mab105120/react-docker-sample:latest
    - name: Generate deployment package
      run: zip -r deploy.zip . -x "*.git*"
    - name: Deploy to EBS
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: react-docker-sample
        environment_name: Reactdockersample-env
        existing_bucket_name: elasticbeanstalk-us-west-2-990613017343
        region: us-west-2
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
